### ISSUE TITLE
[Android] Overlapping maps regression in v0.13.1

### ISSUE THREAD

**Issue by ryankask** [airbnb/react-native-maps#1161]
@lelandrichardson recently merged #1150 to deal with crashes and a memory leak on Android.

The problematic code changed in that PR was added to deal with a longstanding issues (#207 and #453) for Android users rendering more than one `MapView`, one of which isn't supposed to be visible on the screen and is hidden in a `View` with `opacity: 0` (for example).

@fdnhkj submitted #589 to fix the issue but now that the code has been removed.

Is there any way to fix the overlapping issue without causing memory leaks and/or crashes?

**Comment by lelandrichardson** [comment]
@ryankask interesting. Thank you for this context. I'm going to be going through a lot of stuff this weekend for this repo and will try to make sure we get this fixed in a dot release.

Can you help me understand better how #589 fixed issue #453 ?  If you have any context that would be helpful.

We can add back the MapView.initialize(..) call if that was it. That code was not causing any issues, but per google's docs is "unnecessary" since we are cooling getMapAsync in the MapView itself. Perhaps it is what was fixing this bug and we can add it back in.

**Comment by ryankask** [comment]
@lelandrichardson Unfortunatley I lack the Android knowledge to understand @fdnhkj's change. I couldn't find an explanation.

The heart of the issue is which context `MapView` is instantiated with. If I tweak the code to use the activity again, it works. The `initialize()` call doesn't appear to be be related.

Could the activity be used and if it's null, use `reactContext`?

#449 also relates to using the activity albeit in a different way. This PR was mentioned in #589.
