### ISSUE TITLE
proper iOS installation guide

### ISSUE THREAD

**Issue by tishad770** [airbnb/react-native-maps#1304]
The installation guide is clearly not working for integrating Google Maps on iOS. I've searched the issues and they are scrambled so i am confused what the actual steps should be.

**Comment by henrikra** [comment]
I did according to manual installation: https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-3-manually
Try to make fresh project and if you can't still get it working please tell the errors :)

**Comment by tishad770** [comment]
Option 3 doesn't mention anything about GoogleMaps. Should I go with it?

**Comment by tishad770** [comment]
The error says: AirGoogleMaps must be added to your project library.

**Comment by anhtuank7c** [comment]
I have same issue :(

**Comment by M3po** [comment]
I am also having trouble manually adding google maps, Would be great if they add it to Readme

**Comment by anhtuank7c** [comment]
Hum...

**Comment by anhtuank7c** [comment]
@henrikra Do you make it work with google provider on iOS?

**Comment by anhtuank7c** [comment]
I integrated successfully.
Guide here: https://github.com/anhtuank7c/maps-example

**Comment by colus001** [comment]
@anhtuank7c You saved my day. thanks!

**Comment by doomsower** [comment]
Today I spent several hours trying to make react-native-maps work together with some other native libraries. I had react-native 0.45.1 project without cocoapods and with some native modules. Those modules were installed with pure `react-native link` and some of them conflicted with @anhtuank7c method. I had to make following changes:
1. Install `react-native-maps` from master, not from npm (because of #1362 is not yet published )
2. Use this Podfile: 
    ```ruby
    source 'https://github.com/CocoaPods/Specs.git'

    platform :ios, '8.0'

    target 'myprojectname' do
      pod 'GoogleMaps'
    end
    ```
