### ISSUE TITLE
Question: Custom Tiles (Unprojected)

### ISSUE THREAD

**Issue by matt-d-rat** [airbnb/react-native-maps#1460]
Hey, looking for some help in trying to understand how to use ```MapView``` and ```MapView.UrlTile```, with a custom map tile which is unprojected (basically it's a top down view of a video game world).

I've set up my component to render my map. The webserver serving the images is running on localhost:3030

```
<MapView style={styles.map} rotateEnabled={false}>
    <MapView.UrlTile urlTemplate={`http://localhost:3030/map/{z}/{x}/{y}.jpg`} />
</MapView>
```

I can see the MapView is making requests to my server, but it is requesting images which do not exist, given it's current ```{z}/{x}/{y}``` params.

How do I properly configure ```MapView``` with the correct latitude and longitude co-ordinate system for the size of my MapView vs the size of my map image? Maths has never been my strong suit.

The image itself was originally ```1024x1024``` pixels, and each tile I have sliced up to a size of ```256x256``` pixels.

**Comment by fqborges** [comment]
It seems to use the Google tiles standard: https://developers.google.com/maps/documentation/android-api/tileoverlay

**Comment by matt-d-rat** [comment]
After doing a lot of research around this subject it has become to clear to me that I cannot use this component as it assumes that:

1. The world you are mapping is a spheroid (earth)
2. You are using the Web Mercator projection system (Google Maps projection system)

For my purposes the map I am trying to represent is a video game world (flat, not spheroid) and as such would need to change the projection system so that the lat/long coordinates for the map can correctly map to the coordinates of the video game world.

It's a shame because from a performance and UX point of view I would prefer to use this react-native-component. Sadly I will have to settle on using a Web View with a server running Leaflet.js to represent my use case.

**Comment by Stophface** [comment]
@matt-d-rat I am trying to achieve a similar thing. I have the `maptiles` stored on the device and I want to overlay them, using a `Custom Overlay`. In order to run a server I am using https://github.com/futurepress/react-native-static-server which serves on `http://10.0.2.15:8080`. I then add `http://10.0.2.15:8080/{x}{y}{z}.png` and use the `Custom TileOverlay` as instructed. However, it does not return any tiles at all. `react-native-maps` defaults to the standard (on android) google map. I assume my server does not run properly, or the request from ?`react-native-maps` is not send properly. 

It looks like you were able to exactly that step. How did you go on about serving tiles through `localhost:3030`? Whats your stack here and how did you manage to get a `localhost` up and running?

Any help would be very much appreciated!

**Comment by matt-d-rat** [comment]
@Stophface I setup a seperate web-server to serve the files using Node and Express. I abandoned using react-native-maps though because you cannot change the projection system that it uses, so the tiles never correctly mapped (pun intended) to what was shown on screen for the co-ordinates provided (see my previous comment).

**Comment by Stophface** [comment]
@matt-d-rat what did you use instead? Mapbox? Did you set up the web server on the phone?

**Comment by matt-d-rat** [comment]
@Stophface as I mention in my previous comment I ended up using [Leaflet.js](http://leafletjs.com/) running on a standalone web-server (not on the phone). Accessed via a URL displayed in WebView.
