### ISSUE TITLE
Can this component be used in China？

### ISSUE THREAD

**Issue by suuzee** [airbnb/react-native-maps#1477]

**Comment by suuzee** [comment]
I don't know what's going to happen to use Google Maps in China.

**Comment by mattshen** [comment]
Apple Maps should be fine, I reckon.

**Comment by felipecsl** [comment]
AFAIK Google Maps is blocked in China, you'd have to find a different provider.
Also please use this issue tracker for bug reports and features. Questions are better suited for Stack Overflow.

**Comment by suuzee** [comment]
@felipecsl thanks.

**Comment by stephenjen** [comment]
Surprisingly, I've found that this module works in China without VPN on both iOS and Android devices.  Our team has tested the mapping feature of our app numerous times across a period of 2 months from Shanghai, and it works for us.

The problem with our testing is it was all done on US purchased pure Android devices, or devices with Google Play installed over VPN.  This module does not work if Google Play Services is not installed.

Is there a workaround for this problem?

**Comment by alvelig** [comment]
@stephenjen your issue is more an Android SDK, rather than react-native-maps issue. You need to change build.gradle so that it has the dependencies required. You should look for something like this:

[android google maps without google play services](https://www.google.cl/search?q=android+google+maps+without+google+play+services&oq=google+maps+android+without+google+pla&aqs=chrome.1.69i57j0j69i64.8806j0j7&sourceid=chrome&ie=UTF-8)
