### ISSUE TITLE
Memory Release

### ISSUE THREAD

**Issue by sesteva** [airbnb/react-native-maps#149]
Hi,
 Im displaying two maps on two TabBarIOS.Item.
 Memory increases 80MB for each map and even when I switch to a non map tab item, the memory is never released.
 Is there any method I can run on componentWillUnmount to clean up the view?
 Thanks

**Comment by GedoonS** [comment]
I think I'm seeing this too. It appears that when I have a view with the map, open one item on the map, fetch server data, display it, and then return to the map, at some point it crashes on the Nth display of the map, throws an ANR and I see a mem alloc error in logcat. Some garbage collection call on unmount would deffo be great. I'm using a navigator, and pushing new views on it every call. Does that matter? Should I pop before pushing to keep it from piling on?

03-28 13:23:55.411 20555 21054 W art     : Throwing OutOfMemoryError "Failed to allocate a 10800012 byte allocation with 8388608 free bytes and 9MB until OOM"
03-28 13:23:55.429 20555 21054 E AndroidRuntime: FATAL EXCEPTION: Thread-3877
03-28 13:23:55.429 20555 21054 E AndroidRuntime: Process: fi.####, PID: 20555
03-28 13:23:55.429 20555 21054 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 10800012 byte allocation with 8388608 free bytes and 9MB until OOM
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at android.graphics.Bitmap.nativeCreate(Native Method)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:857)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:834)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:801)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.createBitmap(ArtBitmapFactory.java:62)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at com.facebook.imagepipeline.request.BasePostprocessor.process(BasePostprocessor.java:50)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.postprocessInternal(PostprocessorProducer.java:252)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.doPostprocessing(PostprocessorProducer.java:220)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.access$600(PostprocessorProducer.java:78)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer$2.run(PostprocessorProducer.java:178)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
03-28 13:23:55.429 20555 21054 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

**Comment by DennisMG** [comment]
Did you guys find a fix? I'm facing the same problem!

**Comment by GedoonS** [comment]
Thanks for following up. I believe the root of my problem was in using a navigator the wrong way. I had a navigator with several views, one of them being the map. The problem was that I kept pushing more and more views in the navigator, so basically I was running multiple instances of the map at the same time and that crashed the app. I changed my code to not repeatedly push the same views on top of each other, but to pop out the previous views when going from view to view. After this refactoring I haven't had any memory problems with the map. So it was my mistake combined with the fact that the map does reserve quite a lot of memory when it's running.

**Comment by DennisMG** [comment]
How do you manage navigation when you want to go to a previous screen? you push a new view everytime?

**Comment by GedoonS** [comment]
I use `navigator.resetTo(route)` a lot. It pops the stack of previous views and pushes `route`. Mostly the navigator would have been fine, and using pop and push work like they were intended to, but the problems came when we used redux to store in memory where user currently was, and then send them back to that view if the app was closed and opened again. Now when you tried to pop to previous view, but it hadn't been pushed there because the app was just opened, there was no previous view wher the user would go to... That's why we basically rewrote the navigation to just reset the stack every time and manually check what the next scene should be when user pressed HW back or swiped. The next time I'm building an app from scratch I need to think the whole navigation thing over and try and make it work with redux better...

**Comment by DennisMG** [comment]
I see, and how is the performance?  Isn't it a little bit slow to reset the stack everytime?

**Comment by GedoonS** [comment]
It actually seems to perform better this way than by using the navigator as it's supposed to. It's counter intuitive for sure. 
It's my first app ever, so don't take my word for it.Try it out yourself...

**Comment by lelandrichardson** [comment]
This should be fixed now
