### ISSUE TITLE
OnRegionChangeComplete always returns to initialRegion

### ISSUE THREAD

**Issue by sagi** [airbnb/react-native-maps#1507]
## Bug
`onRegionChangeComplete` event resets back to `initialRegion`.

It happens on `iOS` while using `Google Maps` (`PROVIDER_GOOGLE`).

Example (video):

[![onRegionChangeComplete always returns to initialRegion](http://i.imgur.com/0M0auPI.png?1)](https://www.youtube.com/watch?v=m9iyYJp4HR8 "onRegionChangeComplete always returns to initialRegion")

## Reproduction

First we'll need a copy of the `master` branch, lets call it `blaster`:

`$ git checkout -b blaster master`

Now to make it compile (`master` is broken) we'll have to "cherry pick" the following `PR`s:

- #1485 by @Benjamin-Dobell.

Apply it to the `blaster` branch with:
~~~
$ curl https://github.com/airbnb/react-native-maps/commit/e580b706cfed4d7dac8fc2d6bb7d81f5cd3392e5.patch | git am
~~~

- #1503 by myself.

~~~
$ curl https://github.com/airbnb/react-native-maps/commit/32350e26cf7c2be6031dbabf23b8e27cd7269c00.patch | git am
~~~

Now simply:
~~~
$ rm -rf node_modules
$ npm install
~~~

And,
~~~
$ npm run build:ios && npm run run:ios
~~~

**Comment by foyarash** [comment]
Same here using MapKit

**Comment by foyarash** [comment]
The problem seems to come from the setInitialRegion function which is never called.

I tried a workaround like this in the AIRMapManager.m

`RCT_CUSTOM_VIEW_PROPERTY(initialRegion, MKCoordinateRegion, AIRMap)
{
  if (json == nil) return;

  // don't emit region change events when we are setting the region
  BOOL originalIgnore = view.ignoreRegionChanges;
  view.ignoreRegionChanges = YES;
  [view setInitialRegion:[RCTConvert MKCoordinateRegion:json]];
  view.ignoreRegionChanges = originalIgnore;
}`

but it does not work, json variable is nil and I don't know why. I'm not an ObjC developer, so some help would be appreciated :)
