### ISSUE TITLE
customMapStyle prop not working for android

### ISSUE THREAD

**Issue by pcooney10** [airbnb/react-native-maps#1589]
I am using the `customMapStyle` prop to provide a custom style generated on this website: https://mapstyle.withgoogle.com/. I do not have any issues in `ios`, but the `android` app is rendering a beige screen.  I am able to see my markers, but the map image itself is completely beige (with just a small Google logo in the bottom left).

I do not think it's an issue with API keys, as the map renders when the `customMapStyle` prop is omitted. I am also able to see the markers, so I think this might be a bug. 

Versions:
````json
"react": "16.0.0-alpha.12",
"expo": "^19.0.0",
"react-native": "^0.46.1"`
"react-native-maps": "^0.15.3"
````

**Comment by pcooney10** [comment]
Anyone else come across this ?

**Comment by pcooney10** [comment]
bump

**Comment by pcooney10** [comment]
FYI there was an error in my `json` file  🤦. Some of the hex codes had an extra space after them.

Surprised the invalid hex codes were able to work in iOS, but happy my issue has been resolved.

**Comment by breadadams** [comment]
I too was facing this issue (styes working on iOS but not Android), and the culprit was my `json` file 😅 .

However not down to a malformed hex code like @pcooney10 mentions, but instead an empty "top level" `{}` amongst the other map style objects. Removing it allows the custom styles to display on both platforms.
