### ISSUE TITLE
<GoogleMaps/GoogleMaps.h> not found ver 0.12.2, react native 0.37.0. Please help

### ISSUE THREAD

**Issue by 2ducanhpham** [airbnb/react-native-maps#872]
Step:
- Touch Podfile
- Copy Podfile in example and past my podfile
-  Pod install
- Drag node_modules/react-native-maps/ios/AirGoogleMaps/

**Comment by tiemevanveen** [comment]
try `pod 'GoogleMaps', '~> 2.1.1'` in your podfile instead of `pod 'GoogleMaps'` worked for me

**Comment by 2ducanhpham** [comment]
<img width="728" alt="screen shot 2016-12-13 at 10 56 31 am" src="https://cloud.githubusercontent.com/assets/14899775/21127080/db57a01a-c122-11e6-87d7-71fdf6758fac.png">

I'm not run pod install

**Comment by 2ducanhpham** [comment]
I try , but not working

**Comment by oatssss** [comment]
I was having the same issue where I could see `<GoogleMaps/GoogleMaps.h> not found` in the compiler output, but the maps were still working. So I tried opening the Xcode project and tried building it there. It turned out that the Tests bundle was the one that was causing the error. Double checking the search paths for the tests, I found that it was _not_ inheriting the same paths that the app target was. Specifically, it wasn't inheriting the `ios/Pods/Headers/Public` path, which is where `GoogleMaps.h` is.

You could add the path yourself manually, but I just omitted the tests bundle from the build by editing the scheme settings and unchecking "Run" for the Tests bundle. I think the search paths get filled out by `react-native link`? So maybe something can be done fix the search paths for the Tests.

**Comment by 2ducanhpham** [comment]
install 0.15.2 & react native 0.45 -> Worked

**Comment by nonameolsson** [comment]
@2ducanhpham didn't work for me :(
