### ISSUE TITLE
RN 0.40 and React-native-maps 0.12.4 iOS Warning: Native component for "AIRMap" does not exist

### ISSUE THREAD

**Issue by jayhuang75** [airbnb/react-native-maps#969]
Hello All,

I recently update RN 0.40 and react-native-maps 0.12.4.

after the react-link commands. Then android is working perfectly. and for iOS always have the Warning: Native component for "AIRMap" does not exist.

Please advice! Thanks

**Comment by manosim** [comment]
Hello @jayhuang75! Had the same issue yesterday - You need react-native-maps `0.13.0` [Release Details](https://github.com/airbnb/react-native-maps/releases/tag/v0.13.0). I also had to "unlink" and "link" again (not sure if this because of other libraries)

**Comment by jayhuang75** [comment]
@manosim Thanks so much for your help! I still have the same error! Did you remove node_modules/ and update the package.json for reacr-native-maps, then npm install then react-native link?

**Comment by manosim** [comment]
To be honest when things go terribly wrong (especially if you are using more than one libraries with native code) - I would delete the `ios` & `android` directories, also delete `node_modules`, reinstall node modules (make sure you install RN 0.40 & rn-maps 0.13.0), then run `react-native upgrade` (to recreate the ios and android projects) and finally `react-native link`.

Hope it helps!

Ps. Basically if you run `react-native link` without doing the above and if you already have the previous version of rn-maps, it might not override the rn-maps native code in your project so it will not work - hence I am suggesting the above solution.

**Comment by jayhuang75** [comment]
@manosim Thanks for your help I confirm this solution fix the issues!
1. rm -rf ios android node_modules
2. npm install
3. react-native upgrade
4. react-native link

**Comment by jdonald** [comment]
None of the suggestions here fixed my problem when it returned a year later. In my case it turned out to be an instance of #2159 where AirMaps regressed on iOS with the `react-native link` flow. Sure there was an error saying missing GoogleMaps/GoogleMaps.h missing, but that's buried in the spew of `react-native run-ios` or I have to go deep into the AirMaps project in Xcode.

Even once that gets fixed mainline, it goes to show how fragile this is such that future regressions of that sort manifest uselessly as '"AirMAP" does not exist'.
